import "@/app/globals.css";
import theme from "@/lib/ui/theme/theme";
import { ThemeProvider } from "@mui/material/styles";
import { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

export const metadata: Metadata = {
	title: "Trip.note",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ThemeProvider theme={theme}>
			<html lang="en">
				<body style={{ background: "#f3f5f7", margin: 0 }}>
					<AppRouterCacheProvider>{children}</AppRouterCacheProvider>
				</body>
			</html>
		</ThemeProvider>
	);
}
