import "@/app/globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Trip.note",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
